spring:
  application:
    name: Eureka-Provider1
    # 服务端口号
server:
  port: 3001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}